### ISSUE TITLE
JavaScript build without the examples?

### ISSUE THREAD

**Issue by erdalkaraca** [TypeFox/sprotty#128]
I have no experiences with TypeScript et al.
Is there a build with just the sprotty lib to be used in a pure JavaScript project or how to build the sprotty lib without the examples?
Thanks.

**Comment by spoenemann** [comment]
The build options are described in the `scripts` section of [package.json](https://github.com/TypeFox/sprotty/blob/master/client/package.json):

 * `npm run build` builds just the sprotty library, the output directory is `lib`.
 * `npm run examples:build` builds the examples, the output file is `bundle.js`.

**Comment by JanKoehnlein** [comment]
A bit more about this:
TypeScript transpiles to JavaScript, so the library can be consumed by pure JavaScript clients. It also creates a type definition file, such that TypeScript clients can leverage the static type checking.

If you don't want to build sprotty yourself, you can use the pre-built library of the client part including type definitions and source maps from npm: [sprotty at npm](https://www.npmjs.com/package/sprotty), usually by listing a dependency in your `package.json`. It is up to you to write your code in JS, TypeScript, CoffeeScript or whatever..
